=encoding utf8

=head1 为优雅简洁而使用$_

=head2 $_的本地化

在Perl5.10之前，你只能用local来对$_进行本地化，本地化后，你可以在当前范围内使用自己的$_，直到所在作用域结束：

	{
		local $_;
		# ... your local $_
		some_sub(); # 也会使用local的$_
	}

有了local，你可以在限定作用域内随意修改变量，包括在所调用的子程序中仍然可见和有效。

Perl
5.10版本以后，$_开始支持词法域，对它所作的修改，仅限于当下代码的作用域可见，从外部是无法访问的。即便是同一个作用域内所调用的子程序some_sub，也不能访问到词域类型的$_变量：

	{
		my $_;
		# ... your local $_
		some_sub(); # 它看不到你的$_
	}

